data_sources:
  ofgem_annex_4: "https://www.ofgem.gov.uk/sites/default/files/2025-08/policy-cost-allowance-methodology-annex-4.xlsx"
  ofgem_annex_9: "https://www.ofgem.gov.uk/sites/default/files/2025-08/levelisation-allowance-methodology-and-levelised-cap-levels-annex-9.xlsx"

data_downloads:
  annex: "PROJECT_DIR/inputs/data/raw/"
  archetypes: "PROJECT_DIR/asf_levies_model/config/"
