data_sources:
  ofgem_annex_4: "https://www.ofgem.gov.uk/sites/default/files/2025-02/Annex-4-Policy-cost-allowance-methodology-v1.20.xlsx"
  ofgem_annex_9: "https://www.ofgem.gov.uk/sites/default/files/2025-02/Annex-9-Levelisation-allowance-methodology-and-levelised-cap-levels-v1.5.xlsx"

data_downloads:
  annex: "PROJECT_DIR/inputs/data/raw/"
  archetypes: "PROJECT_DIR/asf_levies_model/config/"
